ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MTA,MDL_MW,MDL_MB,MDL_MT,MDL_MH

      COMMON/MASSES/ MDL_MZ,MDL_MTA,MDL_MW,MDL_MB,MDL_MT,MDL_MH


      DOUBLE PRECISION MDL_WT,MDL_WH,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WT,MDL_WH,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_10, GC_11, GC_12

      COMMON/COUPLINGS/ GC_10, GC_11, GC_12

