ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MW,MDL_MT,MDL_MZ,MDL_MB,MDL_MTA,MDL_MH

      COMMON/MASSES/ MDL_MW,MDL_MT,MDL_MZ,MDL_MB,MDL_MTA,MDL_MH


      DOUBLE PRECISION MDL_WW,MDL_WZ,MDL_WT,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WZ,MDL_WT,MDL_WH


      DOUBLE COMPLEX GC_3, GC_50, GC_59

      COMMON/COUPLINGS/ GC_3, GC_50, GC_59

