ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH,MDL_MT,MDL_MW,MDL_MB,MDL_MTA,MDL_MZ

      COMMON/MASSES/ MDL_MH,MDL_MT,MDL_MW,MDL_MB,MDL_MTA,MDL_MZ


      DOUBLE PRECISION MDL_WW,MDL_WZ,MDL_WH,MDL_WT

      COMMON/WIDTHS/ MDL_WW,MDL_WZ,MDL_WH,MDL_WT


      DOUBLE COMPLEX GC_10, GC_11

      COMMON/COUPLINGS/ GC_10, GC_11

