#! /bin/bash

fgdir=/afs/cern.ch/user/a/avalassi/GPU2020/FlameGraph2021/FlameGraph

all= # default: do NOT profile all cpus
if [ "$1" == "-a" ]; then
  all=-a
  shift
fi

frq=1000 # default sampling frequency: 1000 Hertz (1000 frames == 1 second!)
if [ "$1" == "-F" ] && [ "$2" != "" ]; then
  frq="$2"
  shift 2
fi

maxheight= # default max height: unlimited
if [ "$1" == "-h" ] && [ "$2" != "" ]; then
  maxheight="$2"
  shift 2
fi

tag= # default name: perf.svg, else perf-${tag}.svg
if [ "$1" == "-t" ] && [ "$2" != "" ]; then
  tag="-$2"
  shift 2
fi

if ! [[ "$frq" =~ ^[0-9]+$ ]] || [ "$1" == "" ] || [ "$1" != "${1#-F}" ]; then
  echo "Usage: $0 [-a] [-F <Hertz>] [-h <maxheight>] [-t <tag>] <command> [<arguments>]"
  exit 1
fi
cmd="$*"

ldlp=$LD_LIBRARY_PATH

###export PERL5LIB=${fgdir}
export PATH=${fgdir}:${PATH}

###psvg=perf.svg
tag=-$(basename $(hostname) .cern.ch)${tag}
psvg=perf${tag}.svg

set -x

perf record -o perf.data -F ${frq} ${all} --call-graph dwarf -g -- ${cmd}
perf script -i perf.data | stackcollapse-perf.pl > perf.fold
if [ "$maxheight" == "" ]; then
  cat perf.fold > perf.fold2
else
  cat perf.fold | awk -vh=$maxheight '{nf=split($0,a,";"); if (nf<=h){print $1, $2} else {printf a[1]; for (i=2;i<=h;i++) printf ";"a[i]; printf ";STOP[%d>%d] %d\n",nf,h,$2}}' > perf.fold2
fi
flamegraph.pl --minwidth 2 perf.fold2 > ${psvg}

###ls -ltr perf.*

\cp ${psvg} ~/EOS/tmpEOS
###eog ${psvg} &

###perf report --stdio
