      PROGRAM FCHECK_SA
      IMPLICIT NONE
      INCLUDE 'fsampler.inc'
      INCLUDE 'fbridge.inc'
      INTEGER*8 SAMPLER, BRIDGE
      INTEGER NEVT, NEXTERNAL, NP4, NITER
      PARAMETER(NEVT=64, NEXTERNAL=4, NP4=4, NITER=2)
      INTEGER IITER, IEVT
      DOUBLE PRECISION MOMENTA(0:NP4-1, NEXTERNAL, NEVT) ! c-array momenta[nevt][nexternal][np4]
      DOUBLE PRECISION MES(NEVT)
      DOUBLE PRECISION MES_SUM
      MES_SUM = 0
      CALL FBRIDGECREATE(BRIDGE, NEVT, NEXTERNAL, NP4) ! this must be at the beginning as it initialises the CUDA device
      CALL FSAMPLERCREATE(SAMPLER, NEVT, NEXTERNAL, NP4)
      DO IITER = 1, NITER
        CALL FSAMPLERSEQUENCE(SAMPLER, MOMENTA)
        CALL FBRIDGESEQUENCE(BRIDGE, MOMENTA, MES)
        DO IEVT = 1, NEVT
c         WRITE(6,*) 'MES', IEVT, MES(IEVT)
          MES_SUM = MES_SUM + MES(IEVT)
        END DO
c       WRITE(6,*)
      END DO
      CALL FSAMPLERDELETE(SAMPLER)
      CALL FBRIDGEDELETE(BRIDGE) ! this must be at the end as it shuts down the CUDA device
      WRITE(6,*) 'Average Matrix Element:', MES_SUM/NEVT/NITER
      END PROGRAM FCHECK_SA
