ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MH,MDL_MZ,MDL_MB,MDL_MTA,MDL_MW

      COMMON/MASSES/ MDL_MT,MDL_MH,MDL_MZ,MDL_MB,MDL_MTA,MDL_MW


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WT,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WT,MDL_WZ


      DOUBLE COMPLEX GC_3, GC_50, GC_59

      COMMON/COUPLINGS/ GC_3, GC_50, GC_59

