ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of MSSM_SLHA2'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6(1)
      WRITE(*,2) 'GC_55 = ', GC_55(1)
      WRITE(*,2) 'GC_57 = ', GC_57(1)
      WRITE(*,2) 'GC_90 = ', GC_90(1)
