C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(Epsilon(1,2,3,-1)*P(-1,1)) - Epsilon(1,2,3,-1)*P(-1,2)
C     
      SUBROUTINE VVV2_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      TMP1 = (-1D0)*(P1(0)*(V1(4)*(V3(6)*V2(5)-V3(5)*V2(6))+(V1(5)*(
     $ -V3(6)*V2(4)+V3(4)*V2(6))+V1(6)*(V3(5)*V2(4)-V3(4)*V2(5))))
     $ +(P1(1)*(V1(3)*(-V3(6)*V2(5)+V3(5)*V2(6))+(V1(5)*(V3(6)*V2(3)
     $ -V3(3)*V2(6))+V1(6)*(-V3(5)*V2(3)+V3(3)*V2(5))))+(P1(2)*(V1(3)
     $ *(V3(6)*V2(4)-V3(4)*V2(6))+(V1(4)*(-V3(6)*V2(3)+V3(3)*V2(6))
     $ +V1(6)*(V3(4)*V2(3)-V3(3)*V2(4))))+P1(3)*(V1(3)*(-V3(5)*V2(4)
     $ +V3(4)*V2(5))+(V1(4)*(V3(5)*V2(3)-V3(3)*V2(5))+V1(5)*(-V3(4)
     $ *V2(3)+V3(3)*V2(4)))))))
      TMP2 = (-1D0)*(P2(0)*(V1(4)*(V3(6)*V2(5)-V3(5)*V2(6))+(V1(5)*(
     $ -V3(6)*V2(4)+V3(4)*V2(6))+V1(6)*(V3(5)*V2(4)-V3(4)*V2(5))))
     $ +(P2(1)*(V1(3)*(-V3(6)*V2(5)+V3(5)*V2(6))+(V1(5)*(V3(6)*V2(3)
     $ -V3(3)*V2(6))+V1(6)*(-V3(5)*V2(3)+V3(3)*V2(5))))+(P2(2)*(V1(3)
     $ *(V3(6)*V2(4)-V3(4)*V2(6))+(V1(4)*(-V3(6)*V2(3)+V3(3)*V2(6))
     $ +V1(6)*(V3(4)*V2(3)-V3(3)*V2(4))))+P2(3)*(V1(3)*(-V3(5)*V2(4)
     $ +V3(4)*V2(5))+(V1(4)*(V3(5)*V2(3)-V3(3)*V2(5))+V1(5)*(-V3(4)
     $ *V2(3)+V3(3)*V2(4)))))))
      VERTEX = COUP*(+CI*(TMP1+TMP2))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(Epsilon(1,2,3,-1)*P(-1,1)) - Epsilon(1,2,3,-1)*P(-1,2)
C     
      SUBROUTINE VVV2_3_5_6_7_8_9_0(V1, V2, V3, COUP1, COUP2, COUP3,
     $  COUP4, COUP5, COUP6, COUP7,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 COUP7
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL VVV2_0(V1,V2,V3,COUP1,VERTEX)
      CALL VVV3_0(V1,V2,V3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL VVV5_0(V1,V2,V3,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL VVV6_0(V1,V2,V3,COUP4,TMP)
      VERTEX = VERTEX + TMP
      CALL VVV7_0(V1,V2,V3,COUP5,TMP)
      VERTEX = VERTEX + TMP
      CALL VVV8_0(V1,V2,V3,COUP6,TMP)
      VERTEX = VERTEX + TMP
      CALL VVV9_0(V1,V2,V3,COUP7,TMP)
      VERTEX = VERTEX + TMP
      END


