ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MB,MDL_MW,MDL_MTA,MDL_MH,MDL_MT

      COMMON/MASSES/ MDL_MZ,MDL_MB,MDL_MW,MDL_MTA,MDL_MH,MDL_MT


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WT,MDL_WW

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WT,MDL_WW


      DOUBLE COMPLEX GC_10, GC_11, GC_12

      COMMON/COUPLINGS/ GC_10, GC_11, GC_12

