ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH,MDL_MB,MDL_MTA,MDL_MT,MDL_MW,MDL_MZ

      COMMON/MASSES/ MDL_MH,MDL_MB,MDL_MTA,MDL_MT,MDL_MW,MDL_MZ


      DOUBLE PRECISION MDL_WZ,MDL_WT,MDL_WH,MDL_WW

      COMMON/WIDTHS/ MDL_WZ,MDL_WT,MDL_WH,MDL_WW


      DOUBLE COMPLEX GC_3, GC_50, GC_59

      COMMON/COUPLINGS/ GC_3, GC_50, GC_59

