ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-no_b_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4(1)
      WRITE(*,2) 'GC_5 = ', GC_5(1)
      WRITE(*,2) 'GC_11 = ', GC_11
