ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-no_b_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10(1)
      WRITE(*,2) 'GC_11 = ', GC_11(1)
      WRITE(*,2) 'GC_100 = ', GC_100
