ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of heft'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10(1)
      WRITE(*,2) 'GC_11 = ', GC_11(1)
      WRITE(*,2) 'GC_13 = ', GC_13(1)
      WRITE(*,2) 'GC_74 = ', GC_74
