#!/bin/bash
# Copyright (C) 2020-2025 CERN and UCLouvain.
# Licensed under the GNU Lesser General Public License (version 3 or later).
# Created by: D. Massaro (2026) for the MG5aMC CUDACPP plugin.

# Generate the "non-release" form of CUDACPP_SA_OUTPUT/VERSION.txt for a normal
# commit/push on master (the release form is instead generated by archiver.sh).
# The file records the minimal supported MG5aMC version and the last commit block.
# It is committed back to the repository by version_master.yml, so at any time it
# stores the information about the most recent (non version-update) commit.

# Path to the top directory of madgraph4gpu
# In the CI this would be simply $(pwd), but allow the script to be run also outside the CI
echo "Executing $0 $*"
topdir=$(cd $(dirname $0)/../..; pwd)

# Create the VERSION.txt file directly inside the plugin source directory
cd ${topdir}/epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT
outfile=VERSION.txt
dateformat='%Y-%m-%d_%H:%M:%S UTC'
rm -f ${outfile} # remove any pre-existing VERSION.txt before regenerating it
touch ${outfile}
echo "mg5_version_minimal          = $(cat __init__.py | awk '/minimal_mg5amcnlo_version/{print $3}'  | sed 's/(//' | sed 's/)//' | sed 's/,/./g')" >> ${outfile}
echo "" >> ${outfile}
TZ=UTC git --no-pager log -n1 --date=format-local:"${dateformat}" --pretty=format:'commit         %h%nAuthor:        %an%nAuthorDate:    %ad%nCommitter:     %cn%nCommitterDate: %cd%nMessage:       "%s"%n' >> ${outfile}
python3 -c 'print("="*132)'; cat ${outfile}; python3 -c 'print("="*132)'
echo "VERSION.txt file available on $(pwd)/${outfile}"
