ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of EWdim6'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_110 = ', GC_110
      WRITE(*,2) 'GC_113 = ', GC_113
      WRITE(*,2) 'GC_114 = ', GC_114
      WRITE(*,2) 'GC_115 = ', GC_115
      WRITE(*,2) 'GC_145 = ', GC_145
