ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MH,MDL_MW,MDL_MB,MDL_MT,MDL_MTA

      COMMON/MASSES/ MDL_MZ,MDL_MH,MDL_MW,MDL_MB,MDL_MT,MDL_MTA


      DOUBLE PRECISION MDL_WT,MDL_WH,MDL_WZ,MDL_WW

      COMMON/WIDTHS/ MDL_WT,MDL_WH,MDL_WZ,MDL_WW


      DOUBLE COMPLEX GC_10, GC_11

      COMMON/COUPLINGS/ GC_10, GC_11

